{{- $usePSP := (eq (include "loki.rbac.usePodSecurityPolicy" .) "true") }}
{{- $useSCC := (eq (include "loki.rbac.useSecurityContextConstraints" .) "true") }}
{{- if or $usePSP $useSCC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "loki.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "loki.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
