{{- $usePSP := (eq (include "loki.rbac.usePodSecurityPolicy" .) "true") }}
{{- $useSCC := (eq (include "loki.rbac.useSecurityContextConstraints" .) "true") }}
{{- if or $usePSP $useSCC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loki.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
{{- if $usePSP }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "loki.fullname" . }}
{{- end }}
{{- if $useSCC }}
rules:
- apiGroups: 
  - security.openshift.io
  resources: 
  - securitycontextconstraints
  verbs: 
  - use
  resourceNames:
  - {{ include "loki.fullname" . }}
{{- end }}
{{- end }}
