---
patch_rules:

# Changed since mimir 2.0.0, will become defaults
- remove_field: /blocks_storage/bucket_store/chunks_cache/attributes_in_memory_max_items
- remove_field: /blocks_storage/tsdb/isolation_enabled

# filepath-related (doesn't impact functionality)
- remove_field: /activity_tracker/filepath
- remove_field: /alertmanager/data_dir
- remove_field: /blocks_storage/bucket_store/sync_dir
- remove_field: /blocks_storage/tsdb/dir
- remove_field: /compactor/data_dir
- remove_field: /ingester/ring/tokens_file_path
- remove_field: /ruler/rule_path
- remove_field: /runtime_config/file
- remove_field: /store_gateway/sharding_ring/tokens_file_path

# hostnames (doesn't impact functionality)
- remove_field: /alertmanager/external_url
- remove_field: /ruler/alertmanager_url
- remove_field: /blocks_storage/bucket_store/metadata_cache/memcached/addresses
- remove_field: /blocks_storage/bucket_store/index_cache/memcached/addresses
- remove_field: /blocks_storage/bucket_store/chunks_cache/memcached/addresses

# object store configuration
- remove_field: /alertmanager_storage/backend
- remove_field: /alertmanager_storage/gcs/bucket_name
- remove_field: /blocks_storage/backend
- remove_field: /blocks_storage/gcs/bucket_name
- remove_field: /ruler_storage/backend
- remove_field: /ruler_storage/gcs/bucket_name

# ring configuration
- remove_field: /distributor/ha_tracker/kvstore/prefix
- remove_field: /distributor/ring/kvstore/prefix
- remove_field: /store_gateway/sharding_ring/kvstore/prefix

# Jsonnet alertmanager uses consul for ring instead of memberlist
- remove_field: /alertmanager/sharding_ring/kvstore/consul/host
- remove_field: /alertmanager/sharding_ring/kvstore/store

## VVVVVVVVVV Potential Important Things VVVVVVVVVVVVVVVV

# Multitenancy is disabled by default in Helm
- remove_field: /multitenancy_enabled

# Blocks storage, some of this is just flags that aren't set in jsonnet because they aren't used in that component
- remove_field: /blocks_storage/bucket_store/chunks_cache/backend
- remove_field: /blocks_storage/bucket_store/ignore_blocks_within
- remove_field: /blocks_storage/bucket_store/index_cache/backend
- remove_field: /blocks_storage/bucket_store/index_cache/memcached/max_item_size
- remove_field: /blocks_storage/bucket_store/max_chunk_pool_bytes
- remove_field: /blocks_storage/bucket_store/metadata_cache/backend

# Compactor
- remove_field: /compactor/compaction_interval
- remove_field: /compactor/deletion_delay
- remove_field: /compactor/max_closing_blocks_concurrency
- remove_field: /compactor/max_opening_blocks_concurrency
- remove_field: /compactor/sharding_ring/kvstore
- remove_field: /compactor/sharding_ring/wait_stability_min_duration
- remove_field: /compactor/symbols_flushers_concurrency

# Distributor
- remove_field: /distributor/ha_tracker/enable_ha_tracker
- remove_field: /distributor/ha_tracker/kvstore/etcd/endpoints
- remove_field: /distributor/ha_tracker/kvstore/store

# Query Frontend
- remove_field: /frontend_worker/frontend_address
- remove_field: /frontend/align_queries_with_step
- remove_field: /frontend/cache_results
- remove_field: /frontend/log_queries_longer_than
- remove_field: /frontend/results_cache

# Ingester
- remove_field: /ingester/ring/heartbeat_period
- remove_field: /ingester/ring/heartbeat_timeout
- remove_field: /ingester/ring/kvstore
- remove_field: /ingester/ring/num_tokens
- remove_field: /ingester/ring/readiness_check_ring_health

# Limits
- remove_field: /limits/accept_ha_samples
- remove_field: /limits/compactor_tenant_shard_size
- remove_field: /limits/max_cache_freshness
- remove_field: /limits/max_query_length
- remove_field: /limits/ruler_max_rule_groups_per_tenant

# Memberlist
- remove_field: /memberlist/abort_if_cluster_join_fails
- remove_field: /memberlist/compression_enabled
- remove_field: /memberlist/join_members

# Querier
- remove_field: /querier/max_concurrent
- remove_field: /querier/query_store_after

# Server
- remove_field: /server/grpc_server_max_concurrent_streams
- remove_field: /server/grpc_server_max_connection_age
- remove_field: /server/grpc_server_max_connection_age_grace
- remove_field: /server/grpc_server_max_connection_idle
- remove_field: /server/grpc_server_max_recv_msg_size
- remove_field: /server/grpc_server_max_send_msg_size
- remove_field: /server/http_server_write_timeout

# Store-gateway
- remove_field: /store_gateway/sharding_ring/wait_stability_min_duration