config: |
  # Rest of config omitted for clarity.
  # Only configures the admin client S3 storage which is what is
  # used for enterprise authentication, GEx access policies, tenants,
  # and tokens.
  admin_client:
    storage:
      type: "s3"
      s3:
        endpoint: {{ include "enterprise-logs.minio" . }}
        bucket_name: "enterprise-logs-admin"
        secret_access_key: "${AWS_SECRET_KEY}"
        access_key_id: "enterprise-logs"
        insecure: true

# Only configure the configuration file environment expansion for the
# admin-api microservice.
# The environment variable "AWS_SECRET_KEY" is set to the value of the
# "AWS_SECRET_KEY" field in the "s3-secret" Kubernetes Secret.
# This Secret is presumed to exist and is not created by the Helm chart.
#
# To get the admin-api Kubernetes Deployment spec:
# $ helm template ./ -f s3-secret-key.yaml | yq e '. | select(.metadata.name == "RELEASE-NAME-enterprise-logs-admin-api")' -
#
# To check the configuration file:
# $ helm template ./ -f s3-secret-key.yaml | yq e '. | select(.metadata.name == "enterprise-logs-config") | .data."config.yaml"' - | base64 -d
adminApi:
  env:
    - name: "AWS_SECRET_KEY"
      valueFrom:
        secretKeyRef:
          name: "s3-secret"
          key: "AWS_SECRET_KEY"
  extraArgs:
    "config.expand-env": "true"
